# cnn_config.yaml
model:
  type: "cnn"
  shape_in: (3,256,256)  # default: [C=3,W=256,H=256]  
  num_classes: 4  # default: 4
  initial_filters: 64 # default: 8
  num_fc1: 100  # default: 100
  dropout_rate: 0.25  # default: 0.25

train:
  skip_loading: false # set true if you want to use the existing data in output folder.
  data:
    dataset: "data/raw_data/brain-tumor-classification-mri/Training" # raw data
    # !! if skip_loading == False, run this training WILL DELETE THIS 'output' DIRECTORY TO REMOVE DATA FROM PREVIOUS TRAINING WITH YOUR PERMISSION.
    output: "data/processed_data/brain-tumor-classification-mri" 
    train_set: "train" # path to train_set: output/train_set 
    val_set: "val" # path to val_set: output/valset
  load: # if skip_loading == True, this subblock is ignored.
    train_ratio: 0.8 # default: 0.8 split folders into train and val sets by this ratio
    image_size: (256,256) # default: [H=256,W=256] transform to this image size. 
  mlflow:
    enabled: false
    uri: "http://localhost:5000"
    experiment: "TuneCNN"
  batch_size: 32 # default: 64
  epochs: 30
  learning_rate: 3e-4 # default: 3e-4
  verbose: true
  device: 'cpu' # most commonly “cpu” or “cuda”, but also potentially “mps”, “xpu”, “xla” or “meta”.
  save_path: "checkpoints/cnn_model"
  checkpoint_name: "test.pt"

eval:
  model: "checkpoints/cnn_model/tunecnn/Exp_10.pt"
  image_size: (256,256)
  batch_size: 32 # default: 32
  data: "data/raw_data/brain-tumor-classification-mri/Testing"
  device: 'cpu'
  report: "output/Exp_10.md"

deploy:
  model: "checkpoints/deployed_models/cnn_model.pt"
  input: "data/processed_data/brain-tumor-classification-mri/train/glioma_tumor/image.jpg"  # Path to the input image
  device: 'cpu'

