# cnn_config.yaml
model:
  type: "cnn"
  shape_in: [3,256,256]  # default: [3,256,256]  
  num_classes: 4  # default: 4
  initial_filters: 8 # default: 8
  num_fc1: 100  # default: 100
  dropout_rate: 0.25  # default: 0.25
  save_path: "models/cnn_model/cnn_model_trained_only_by_Testing.pt"

data:
  dataset_path: "data/raw_data/brain-tumor-classification-mri/Testing"
  output_path: "data/processed_data/brain-tumor-classification-mri"
  train_path: "data/processed_data/brain-tumor-classification-mri/train"
  val_path: "data/processed_data/brain-tumor-classification-mri/val"

loading:
  train_ratio: 0.8 # default: 0.8 split folders into train and val sets by this ratio
  image_size: [256,256] # default: [256,256] transform to this image size. 

training:
  batch_size: 64 # default: 64
  epochs: 50
  learning_rate: 3e-4 # default: 3e-4
  verbose: true
  device: 'cpu'

evaluation:
  batch_size: 64 # default: 64
  path: "data/raw_data/brain-tumor-classification-mri/Training"
  model_wts: "models/cnn_model/cnn_model_trained_only_by_Testing.pt"
  device: 'cpu'
  report_path: "output/report_trainedonlyTesting_cnn_model_data_Training.md"

mlflow:
  enabled: true
  tracking_uri: "http://localhost:5000"
  experiment_name: "MRI_Classifier"