# inference_config.yaml
device: "cpu"  # Options: "cuda" or "cpu"

cnn:
  model_path: "models/cnn_model/cnn_model.pth"
  shape_in: [3,256,256]
  num_classes: 4
  initial_filters: 8
  num_fc1: 100
  dropout_rate: 0.25
  input_image_path: "scripts/test_2dmri.jpg"  # Path to the input image

unet3d:
  model_path: "models/unet_model/unet_model.pth"
  in_channels: 4
  out_channels: 4
  input_volume_path: "scripts/test_3dvol.nii"  # Path to the input 3D volume
  output_path: "output/segmented_volume.nii"  # Path to save the output segmented volume
