# Configuration for 3D UNet Model
model:
  type : "unet3d"
  in_channels: 4                # Number of input channels (e.g., 1 for grayscale MRI)
  out_channels: 4              # Number of output channels (e.g., 1 for binary segmentation)

train:
  data:
    data_path: "data/"     # Path to the training dataset (3D volumes)
    cache_path: "data/cache_dir"
    image_folder: "imageTr"
    label_folder: "labelTr"

  mlflow:
    enabled: true                 # Enable MLflow logging
    uri: "http://localhost:5000"  # MLflow server URI
    experiment: "3D_UNet_MRI_Segmentation"  # Name of the MLflow experiment
  batch_size: 1                 # Batch size (adjust based on available GPU memory)
  epochs: 20                 # Number of training epochs
  learning_rate: 0.0001         # Learning rate for the optimizer
  verbose: true
  device: 'cpu'
  save_path: "models/unet_model/unet_20nii_20epoch.pt"

eval:
  model: "models/saved_models/unet_model.pt"
  batch_size: 1                
  data: "data"
  device: 'cpu'
  report: "output/evaluation_report_unet.md"

deploy:
  model: "models/deployed_models/unet_model.pt"
  input: "data/imageTr/BRATS_001.nii.gz"  # Path to the input image
  device: 'cpu'
  output: "output/segmented_volume.nii"


